package br.com.fatec.view;

import br.com.fatec.util.BancoConexao;
import br.com.fatec.controller.GerenciarVisitaController;
import br.com.fatec.util.Mascaras;
import br.com.fatec.model.Visitante;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno.a.da.silva
 */
public class GerenciarVisita extends javax.swing.JInternalFrame {

    private GerenciarVisitaController ger = new GerenciarVisitaController();
    /**
     * Creates new form GerenciarVisita
     */
    public GerenciarVisita() {
        initComponents();
        limparCampos();
    }
    
    private void limparCampos(){
        txtNome.setText("");
        txtValor.setText("");
        txtNome.setEditable(false);
        txtValor.setEditable(false);
        btIniciar.setEnabled(false);
        btFinalizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusca = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        btIniciar = new javax.swing.JButton();
        btFinalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gerenciar Visita");

        txtBusca.setFormatterFactory(Mascaras.cpf());

        jLabel1.setText("CPF do visitante:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btIniciar.setText("Iniciar Visita");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        btFinalizar.setText("Finalizar Visita");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Visitante:");

        jLabel3.setText("Valor: R$");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(txtNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btFinalizar)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btBuscar)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btLimpar))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIniciar)
                    .addComponent(btFinalizar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        if(txtBusca.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(this, "Preecha o campo de busca", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                Visitante visit = ger.consultarVisitante(txtBusca.getText());
                txtNome.setText(visit.getNome());
                txtValor.setText(String.valueOf(ger.valorEntrada(visit.getCpf())));
                btIniciar.setEnabled(true);
                btFinalizar.setEnabled(true);
            }catch(NullPointerException ex){
                JOptionPane.showMessageDialog(this, "Visitante não encontrado!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro : " + ex.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        // TODO add your handling code here:
        if(txtBusca.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(this, "Digite o CPF do visitante e clique em buscar", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                ger.iniciarVisita(txtBusca.getText());
                JOptionPane.showMessageDialog(this, "Visita iniciada!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this, "Erro de banco de dados: " + e.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException | NullPointerException ex) {
                Logger.getLogger(GerenciarVisita.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btIniciarActionPerformed

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(txtBusca.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(this, "Digite o CPF do visitante e clique em buscar", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                BancoConexao.conectar();
                PreparedStatement stm = BancoConexao.getConexao()
                        .prepareStatement("select codigo,dataHoraEntrada, dataHoraSaida from visita "
                                + "where visitante_idVisitante = "
                                + "(select max(idVisitante) from visitante "
                                + "where cpf = '" + txtBusca.getText() + "') order by codigo desc");
                ResultSet rs = stm.executeQuery();                
                if (rs.next()) { 
                    System.out.println(rs.getBoolean("dataHoraSaida"));
                    if(rs.getString("dataHoraSaida")!=null){
                        JOptionPane.showMessageDialog(this, "Visitante não iniciou visita!", "Alerta", JOptionPane.ERROR_MESSAGE);
                        rs.close();
                        BancoConexao.desconectar();
                        return;
                    }
                    else{
                        ger.encerrarVisita(txtBusca.getText());
                        JOptionPane.showMessageDialog(this, "Visita Finalizada!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                rs.close();
                BancoConexao.desconectar();
            }catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this, "Erro de banco de dados: " + e.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException | NullPointerException ex) {
                Logger.getLogger(GerenciarVisita.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btFinalizar;
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtBusca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
