package br.com.fatec.view;

import br.com.fatec.controller.AcervoController;
import br.com.fatec.controller.RestauracaoController;
import br.com.fatec.enums.StatusRestauracao;
import br.com.fatec.model.Obra;
import br.com.fatec.model.Restauracao;
import br.com.fatec.model.Restaurador;
import br.com.fatec.util.Mascaras;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class GerenciarRestauracao extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciarRestauracao
     */
    private String imagemCaminho;
    private final RestauracaoController ger = new RestauracaoController();
    private final AcervoController gerAcervo = new AcervoController();
    
    public GerenciarRestauracao() throws SQLException, ClassNotFoundException, NullPointerException {
        initComponents();
        limparCampos();
        DefaultComboBoxModel model = new DefaultComboBoxModel(StatusRestauracao.values());
        lbStatus.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscaObra = new javax.swing.JTextField();
        btBuscarObra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAutorObra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JFormattedTextField();
        btLimpar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        cbRestaurador = new javax.swing.JComboBox<>();
        cbObra = new javax.swing.JComboBox<>();
        lbStatus = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Gerenciar Restauração");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatec/images/Restauracao.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Buscar Obra:");

        btBuscarObra.setText("Buscar");
        btBuscarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarObraActionPerformed(evt);
            }
        });

        jLabel2.setText("Obra:");

        jLabel3.setText("Autor:");

        txtAutorObra.setEditable(false);

        jLabel4.setText("Valor da restauração: R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setText("Status Restauração:");

        jLabel6.setText("Restaurador:");

        jLabel7.setText("Data Inicío:");

        txtDataInicio.setFormatterFactory(Mascaras.data());

        jLabel8.setText("Data Encerramento:");

        txtDataFim.setFormatterFactory(Mascaras.data());

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        cbRestaurador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbObraActionPerformed(evt);
            }
        });

        lbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbRestaurador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtValor)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btAtualizar)
                                .addGap(52, 52, 52)
                                .addComponent(btExcluir)
                                .addGap(41, 41, 41)))
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(txtBuscaObra, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscarObra))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbObra, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAutorObra, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btLimpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btCadastrar))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarObra))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(cbRestaurador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAutorObra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btCadastrar)
                    .addComponent(btAtualizar)
                    .addComponent(btExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void popularCombo() throws SQLException, ClassNotFoundException, NullPointerException {
        ArrayList<Obra> obras = (ArrayList) gerAcervo.listarObras("where codigo not in (select obra_codigo from restauracao where status !='FINALIZADA')");       
        ArrayList<String> nome= new ArrayList<>();
        for(Obra obra : obras){
            nome.add(obra.getNome());
        }
        Object[] array = nome.toArray();
        DefaultComboBoxModel model = new DefaultComboBoxModel(array);
        cbObra.setModel(model);
        if(!obras.isEmpty()){
            txtAutorObra.setText(obras.get(0).getAutor());
        }else{
            txtAutorObra.setText("");
        }
        ArrayList<Restaurador> restauradores = (ArrayList) ger.listarRestaurador("where cracha not in (select restaurador_cracha from restauracao where status !='FINALIZADA')");
        nome = new ArrayList<>();
        for(Restaurador restaurador : restauradores){
            nome.add(restaurador.getNome());
        }
        array = nome.toArray();
        model = new DefaultComboBoxModel(array);
        cbRestaurador.setModel(model);
    }
    
    private void limparCampos() throws SQLException, ClassNotFoundException, NullPointerException {
        txtAutorObra.setText("");
        txtBuscaObra.setText("");
        cbRestaurador.setSelectedIndex(0);
        
        txtDataFim.setText("");
        txtDataInicio.setText("");
        txtValor.setText("");
        
        btAtualizar.setEnabled(false);
        btExcluir.setEnabled(false);
        
        lbStatus.setSelectedIndex(0);
        btCadastrar.setEnabled(true);
        cbObra.setEnabled(true);
        popularCombo();
        cbObra.setEnabled(true);
        cbRestaurador.setEnabled(true);
        lbStatus.setSelectedItem(StatusRestauracao.NOVA);
        lbStatus.setEnabled(false);
        txtDataInicio.setEnabled(true);
        txtDataFim.setEnabled(true);
        txtValor.setEnabled(true);
        
    }
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        try {
            // TODO add your handling code here:
            limparCampos();
        } catch (SQLException | ClassNotFoundException | NullPointerException ex) {
            Logger.getLogger(GerenciarRestauracao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        if(cbObra.getSelectedItem().equals("") || txtValor.getText().equals("") || cbObra.getSelectedItem() == null || cbRestaurador.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Preenhca os campos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                ger.registrarRestauracao(cbRestaurador.getSelectedItem().toString(),
                        gerAcervo.consultarObra(cbObra.getSelectedItem().toString()),
                        txtValor.getText(), txtDataInicio.getText(),
                        txtDataFim.getText());
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            } catch (SQLException | ClassNotFoundException | NullPointerException ex) {
                Logger.getLogger(GerenciarRestauracao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void cbObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbObraActionPerformed
        try {
            // TODO add your handling code here:
            Obra obra = gerAcervo.consultarObra(cbObra.getSelectedItem().toString());
            txtAutorObra.setText(obra.getAutor());
            lbImagem.setIcon(ResizeImage(obra.getCaminhoImg()));
            imagemCaminho = obra.getCaminhoImg();
        } catch (SQLException | ClassNotFoundException | NullPointerException ex) {
            Logger.getLogger(GerenciarRestauracao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbObraActionPerformed

    private void btBuscarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarObraActionPerformed
        // TODO add your handling code here:
        if(txtBuscaObra.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de busca!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                Restauracao restauracao = ger.consultarRestauracao(txtBuscaObra.getText());
                txtAutorObra.setText(restauracao.getObra().getAutor());
                lbImagem.setIcon(ResizeImage(restauracao.getObra().getCaminhoImg()));
                imagemCaminho = restauracao.getObra().getCaminhoImg();
                lbStatus.setSelectedItem(restauracao.getStatus());
                cbObra.setSelectedItem(restauracao.getObra().getNome());
                cbRestaurador.setSelectedItem(restauracao.getRestaurador().getNome());
                System.out.println(restauracao.getRestaurador().getNome());
                txtValor.setText(String.valueOf(restauracao.getValor()));
                
                if(restauracao.getDataInicio() != null){
                    Calendar data =restauracao.getDataInicio();
                    txtDataInicio.setText(formataData(data));                
                    if(restauracao.getDataFim() != null){
                        data = restauracao.getDataFim();                
                        txtDataFim.setText(formataData(data));
                    }
                    else{
                        txtDataFim.setText("");
                    }
                }
                else{
                    txtDataInicio.setText("");
                }
                ArrayList<Obra> obras = (ArrayList) gerAcervo.listarObras("where codigo ="+restauracao.getObra().getCodigo());       
                ArrayList<String> nome= new ArrayList<>();
                for(Obra obra : obras){
                    nome.add(obra.getNome());
                }
                Object[] array = nome.toArray();
                DefaultComboBoxModel model = new DefaultComboBoxModel(array);
                cbObra.setModel(model);
                ArrayList<Restaurador> restauradores = (ArrayList) ger.listarRestaurador("where cracha not in "
                        + "(select restaurador_cracha from restauracao where codigo !="+restauracao.getCodigo()+")");
                 nome = new ArrayList<>();
                for(Restaurador restaurador : restauradores){
                    nome.add(restaurador.getNome());
                }
                array = nome.toArray();
                model = new DefaultComboBoxModel(array);
                cbRestaurador.setModel(model);
                cbRestaurador.setSelectedItem(restauracao.getRestaurador().getNome());
                if(restauracao.getStatus() == StatusRestauracao.FINALIZADA){
                    cbObra.setEnabled(false);
                    lbStatus.setEnabled(false);
                    txtDataInicio.setEnabled(false);
                    txtDataFim.setEnabled(false);
                    txtValor.setEnabled(false);
                    btCadastrar.setEnabled(false);
                    btAtualizar.setEnabled(false);
                    btExcluir.setEnabled(true);
                    cbRestaurador.setEnabled(false);
                }else{
                    lbStatus.setEnabled(true);
                    btCadastrar.setEnabled(false);
                    btAtualizar.setEnabled(true);
                    btExcluir.setEnabled(true);
                    cbObra.setEnabled(false);
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(GerenciarRestauracao.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(this, "Restauração não encontrada!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btBuscarObraActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esse registro?", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        if(opc==JOptionPane.YES_OPTION){
            try {
                ger.excluirRestauracao(cbObra.getSelectedItem().toString());
                JOptionPane.showMessageDialog(this, "Removido com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }catch(NullPointerException ex){
                Logger.getLogger(CadastroAcervo.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Restauração não encontrada!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CadastroAcervo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        if(cbObra.getSelectedItem().equals("") || txtValor.getText().equals("") || txtDataInicio.getText().equals("    -  -  ")){
            JOptionPane.showMessageDialog(null, "Preenhca os campos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                ger.alterarRestauracao(cbRestaurador.getSelectedItem().toString(),
                        gerAcervo.consultarObra(cbObra.getSelectedItem().toString()),
                        txtValor.getText(), txtDataInicio.getText(),
                        txtDataFim.getText(),
                        (StatusRestauracao) lbStatus.getSelectedItem());
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            } catch (SQLException | ClassNotFoundException | NullPointerException ex) {
                Logger.getLogger(GerenciarRestauracao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btAtualizarActionPerformed
    
    private String formataData(Calendar data){
        String formatada =""+data.get(Calendar.YEAR)
                        +"-"+(data.get(Calendar.MONTH)+1)
                        +"-"+data.get(Calendar.DAY_OF_MONTH);
        return formatada;
    }
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbImagem.getWidth(), lbImagem.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imagem = new ImageIcon(newImg);
        return imagem;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscarObra;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JComboBox<String> cbObra;
    private javax.swing.JComboBox<String> cbRestaurador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JComboBox<String> lbStatus;
    private javax.swing.JTextField txtAutorObra;
    private javax.swing.JTextField txtBuscaObra;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
