package br.com.fatec.view;

import br.com.fatec.controller.AcervoController;
import br.com.fatec.controller.RestauracaoController;
import br.com.fatec.model.Obra;
import br.com.fatec.model.Restauracao;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class StatusObras extends javax.swing.JInternalFrame {
    
    private final AcervoController acervo = new AcervoController();
    private final RestauracaoController restauracao = new RestauracaoController();
    /**
     * Creates new form StatusObras
     */
    @Deprecated
    public StatusObras() {
        initComponents();
    }
    
    public StatusObras(String consulta){
        initComponents();
        switch(consulta){
            case "StatusObras":
                carregarStatusObras();
                break;
            case "StatusRestauracoes":
                carregarRestauracoes();
                break;            
        }
    }
    
    public void carregarStatusObras(){        
        try {
            DefaultTableModel model = new DefaultTableModel(new String[] {"Nome Obra", "Autor", "Tipo de Obra", "Status", "Exposição"},0);
            List<Obra> obras = acervo.listarObras("");            
            Iterator<Obra> obrIt = obras.iterator();
            while(obrIt.hasNext()){
                Obra obra = obrIt.next();
                if(obra.getExposicao() == null){
                    model.addRow(new Object[]{obra.getNome(), obra.getAutor(),obra.getClassificacao().toString(), obra.getStatus().toString()});
                }else{
                    model.addRow(new Object[]{obra.getNome(), obra.getAutor(),obra.getClassificacao().toString(), obra.getStatus().toString(), obra.getExposicao().getNome()});
                }
                tbObras.setModel(model);
                tbObras.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StatusObras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StatusObras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(StatusObras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void carregarRestauracoes(){        
        try {
            Calendar data;
            String inicio, fim;
            DefaultTableModel model = new DefaultTableModel(new String[] {"Nome Obra", "Autor", "Tipo de Obra", "Status Restauração", "Restaurador", "Início", "Fim"},0);
            List<Restauracao> restauracoes = restauracao.listarRestauracao("");            
            Iterator<Restauracao> restIt = restauracoes.iterator();
            while(restIt.hasNext()){
                Restauracao restauracao = restIt.next();
                    data =restauracao.getDataInicio();                
                    inicio =""+data.get(Calendar.DAY_OF_MONTH)
                            +"-"+(data.get(Calendar.MONTH)+1)
                            +"-"+data.get(Calendar.YEAR);
                    data = restauracao.getDataFim();
                    fim =""+data.get(Calendar.DAY_OF_MONTH)
                            +"-"+(data.get(Calendar.MONTH)+1)
                            +"-"+data.get(Calendar.YEAR);
                    model.addRow(new Object[]{restauracao.getObra().getNome(), 
                    restauracao.getObra().getAutor(), restauracao.getObra().getClassificacao().toString(), 
                    restauracao.getStatus().toString(), restauracao.getRestaurador().getNome(), 
                    inicio, fim});

                tbObras.setModel(model);
                tbObras.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StatusObras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StatusObras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(StatusObras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbObras = new javax.swing.JTable();

        setClosable(true);
        setTitle("Status das Obras");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fatec/images/Obra.png"))); // NOI18N

        tbObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbObras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbObras;
    // End of variables declaration//GEN-END:variables
}
